fix: fix generated types to missing import (#86)
Got this error when using this in lodestar

```
@chainsafe/lodestar: $ tsc -p tsconfig.build.json
@chainsafe/lodestar: ../../node_modules/datastore-core/types/src/index.d.ts:20:23 - error TS2304: Cannot find name 'ShardImport'.
@chainsafe/lodestar: 20     ShardBase: typeof ShardImport.ShardBase;
@chainsafe/lodestar:                          ~~~~~~~~~~~
@chainsafe/lodestar: ../../node_modules/datastore-core/types/src/index.d.ts:21:20 - error TS2304: Cannot find name 'ShardImport'.
@chainsafe/lodestar: 21     Prefix: typeof ShardImport.Prefix;
@chainsafe/lodestar:                       ~~~~~~~~~~~
@chainsafe/lodestar: ../../node_modules/datastore-core/types/src/index.d.ts:22:20 - error TS2304: Cannot find name 'ShardImport'.
@chainsafe/lodestar: 22     Suffix: typeof ShardImport.Suffix;
@chainsafe/lodestar:                       ~~~~~~~~~~~
@chainsafe/lodestar: ../../node_modules/datastore-core/types/src/index.d.ts:23:24 - error TS2304: Cannot find name 'ShardImport'.
@chainsafe/lodestar: 23     NextToLast: typeof ShardImport.NextToLast;
@chainsafe/lodestar:                           ~~~~~~~~~~~
@chainsafe/lodestar: Found 4 errors.
@chainsafe/lodestar: error Command failed with exit code 2.
```

Fixes: #85